import { NextPage } from 'next';
import Head from 'next/head';

import { Header, Main } from '../components/Layout';
import { RepositoryList } from '../components/RepositoryList';
import { SearchBar } from '../components/SearchBar';

const Home: NextPage = () => (
  <>
    <Head>
      <title>GitHub Repo Searcher</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <Header />
    <Main>
      <SearchBar />

      <RepositoryList />
    </Main>
  </>
);

export default Home;
